"""Metrics catalog — measurement methodologies for each target hardware metric.

NOTE: No probe_template references — all code is generated by the LLM at runtime.
The strategies describe *what* to measure and *how* (methodology), not pre-built code.
"""

from __future__ import annotations

from core.models import MetricSpec, ProbeStrategy


def build_catalog() -> dict[str, MetricSpec]:
    """Return the full catalog of supported hardware metrics and their probe strategies."""
    catalog = {
        "dram_latency_cycles": MetricSpec(
            name="dram_latency_cycles",
            description="DRAM (global memory) access latency in GPU clock cycles",
            unit="cycles",
            strategies=[
                ProbeStrategy(
                    name="pointer_chase_large",
                    probe_template=None,
                    params={"DATA_SIZE_BYTES": 256 * 1024 * 1024, "ITERATIONS": 1000, "WARMUP": 100},
                    priority=1,
                    description="Pointer chasing over 256MB array (exceeds L2) to measure DRAM latency. "
                    "Single-thread kernel, random permutation chain, clock64() timing.",
                ),
                ProbeStrategy(
                    name="pointer_chase_sequential",
                    probe_template=None,
                    params={"DATA_SIZE_BYTES": 512 * 1024 * 1024, "ITERATIONS": 500, "WARMUP": 50},
                    priority=2,
                    description="Pointer chasing over 512MB array to force DRAM access. "
                    "Larger array to ensure full L2 miss.",
                ),
            ],
            cross_verify=True,
            tolerance_pct=10,
            physical_min=200,
            physical_max=1500,
        ),
        "l1_latency_cycles": MetricSpec(
            name="l1_latency_cycles",
            description="L1 cache access latency in GPU clock cycles",
            unit="cycles",
            strategies=[
                ProbeStrategy(
                    name="pointer_chase_small",
                    probe_template=None,
                    params={"DATA_SIZE_BYTES": 8 * 1024, "ITERATIONS": 5000, "WARMUP": 500},
                    priority=1,
                    description="Pointer chasing over 8KB array (fits entirely in L1 cache). "
                    "Single-thread, random chain, clock64() timing. Expect 20-40 cycles.",
                ),
            ],
            cross_verify=False,
            tolerance_pct=15,
            physical_min=10,
            physical_max=80,
        ),
        "l2_latency_cycles": MetricSpec(
            name="l2_latency_cycles",
            description="L2 cache access latency in GPU clock cycles",
            unit="cycles",
            strategies=[
                ProbeStrategy(
                    name="pointer_chase_medium",
                    probe_template=None,
                    params={"DATA_SIZE_BYTES": 512 * 1024, "ITERATIONS": 2000, "WARMUP": 200},
                    priority=1,
                    description="Pointer chasing over 512KB array (exceeds L1 ~128KB, fits in L2). "
                    "Measures L2 hit latency. Expect 100-300 cycles.",
                ),
            ],
            cross_verify=False,
            tolerance_pct=10,
            physical_min=100,
            physical_max=500,
        ),
        "l2_cache_size_kb": MetricSpec(
            name="l2_cache_size_kb",
            description="L2 cache capacity in kilobytes",
            unit="KB",
            strategies=[
                ProbeStrategy(
                    name="cache_sweep",
                    probe_template=None,
                    params={"MIN_KB": 64, "MAX_KB": 65536, "STEPS": 24, "ITERATIONS": 500, "WARMUP": 100},
                    priority=1,
                    description="Logarithmic sweep of data sizes from 64KB to 64MB, "
                    "running pointer chase at each size. Detect latency cliff where "
                    "data exceeds L2. The size just before the cliff is the L2 capacity.",
                ),
            ],
            cross_verify=False,
            tolerance_pct=5,
            physical_min=256,
            physical_max=131072,
        ),
        "max_global_mem_bandwidth_gb_s": MetricSpec(
            name="max_global_mem_bandwidth_gb_s",
            description="Peak achievable global memory (VRAM) bandwidth in GB/s",
            unit="GB/s",
            strategies=[
                ProbeStrategy(
                    name="bandwidth_stream",
                    probe_template=None,
                    params={"DATA_SIZE_BYTES": 256 * 1024 * 1024, "ITERATIONS": 20, "WARMUP": 5, "BLOCK_SIZE": 256},
                    priority=1,
                    description="Streaming copy and read-only kernels using float4 for coalesced access. "
                    "Large buffer (256MB), multiple SMs active. Report max of copy and read BW.",
                ),
                ProbeStrategy(
                    name="bandwidth_ncu",
                    probe_template=None,
                    ncu_metrics=["dram__throughput.avg.pct_of_peak_sustained_elapsed", "dram__bytes.sum"],
                    needs_ncu=True,
                    priority=2,
                    description="Use ncu to measure DRAM throughput directly via hardware counters.",
                ),
            ],
            cross_verify=True,
            tolerance_pct=5,
            physical_min=10,
            physical_max=5000,
        ),
        "max_shmem_bandwidth_gb_s": MetricSpec(
            name="max_shmem_bandwidth_gb_s",
            description="Peak achievable shared memory bandwidth in GB/s",
            unit="GB/s",
            strategies=[
                ProbeStrategy(
                    name="bandwidth_shmem",
                    probe_template=None,
                    params={"BLOCK_SIZE": 256, "ITERATIONS": 1000, "WARMUP": 100},
                    priority=1,
                    description="Conflict-free shared memory read+write (4 floats per thread, "
                    "sequential access within warp). Launch on all SMs. "
                    "Total bytes = num_blocks * block_size * 32 * iterations.",
                ),
            ],
            cross_verify=False,
            tolerance_pct=10,
            physical_min=1,
            physical_max=50000,
        ),
        "actual_boost_clock_mhz": MetricSpec(
            name="actual_boost_clock_mhz",
            description="Actual sustained GPU core clock frequency under load in MHz",
            unit="MHz",
            strategies=[
                ProbeStrategy(
                    name="fma_clock_probe",
                    probe_template=None,
                    params={"FMA_ITERATIONS": 1000000, "WARMUP_ITERATIONS": 100000, "TRIALS": 5},
                    priority=1,
                    description="Run known number of FMA ops on all SMs. Measure wall time "
                    "via CUDA events and cycle count via clock64(). "
                    "Frequency = cycles / time. Multiple trials, average excluding first.",
                ),
                ProbeStrategy(
                    name="nvidia_smi_clock",
                    probe_template=None,
                    params={"USE_NVIDIA_SMI": 1},
                    priority=3,
                    description="Read clock from nvidia-smi (may be inaccurate if frequency locked). "
                    "Generate a simple CUDA kernel that keeps GPU busy while reading nvidia-smi.",
                ),
            ],
            cross_verify=True,
            tolerance_pct=2,
            physical_min=100,
            physical_max=3500,
        ),
        "bank_conflict_penalty_cycles": MetricSpec(
            name="bank_conflict_penalty_cycles",
            description="Latency penalty of a shared memory bank conflict vs conflict-free access",
            unit="cycles",
            strategies=[
                ProbeStrategy(
                    name="bank_conflict_probe",
                    probe_template=None,
                    params={"BLOCK_SIZE": 256, "ITERATIONS": 10000, "WARMUP": 1000},
                    priority=1,
                    description="Two kernels: (1) conflict-free: thread k reads smem[k], "
                    "(2) conflicting: all threads read same bank (stride 32). "
                    "Penalty = conflict_avg - no_conflict_avg cycles per iteration.",
                ),
            ],
            cross_verify=False,
            tolerance_pct=20,
            physical_min=0,
            physical_max=100,
        ),
        "max_shmem_per_block_kb": MetricSpec(
            name="max_shmem_per_block_kb",
            description="Maximum shared memory per thread block in KB",
            unit="KB",
            strategies=[
                ProbeStrategy(
                    name="shmem_alloc_probe",
                    probe_template=None,
                    params={"START_KB": 16, "MAX_KB": 228, "STEP_KB": 4},
                    priority=1,
                    description="Linear scan from 16KB upward in 4KB steps. "
                    "Use cudaFuncSetAttribute for extended shared memory. "
                    "Try launching kernel at each size. Max = largest successful size.",
                ),
            ],
            cross_verify=False,
            tolerance_pct=0,
            physical_min=16,
            physical_max=228,
        ),
        "physical_sm_count": MetricSpec(
            name="physical_sm_count",
            description="Physical number of Streaming Multiprocessors on the GPU die, "
            "measured via direct micro-benchmark (NOT cudaGetDeviceProperties)",
            unit="count",
            strategies=[
                ProbeStrategy(
                    name="sm_count_residency",
                    probe_template=None,
                    params={"BLOCK_SIZE": 1, "MAX_BLOCKS": 256, "ITERATIONS": 100},
                    priority=1,
                    description="Launch 1-thread blocks with infinite loop. Increase block count "
                    "until kernel occupancy saturates. Each SM can run at least one block. "
                    "Use atomicAdd from each block's unique smid (read via %smid PTX) to "
                    "count distinct SM IDs. This gives the true physical SM count.",
                ),
                ProbeStrategy(
                    name="sm_count_smid",
                    probe_template=None,
                    params={"NUM_BLOCKS": 256, "BLOCK_SIZE": 32},
                    priority=2,
                    description="Launch many blocks, each reads %smid via inline PTX asm. "
                    "Collect all unique SM IDs into a device array using atomicCAS. "
                    "Count of unique IDs = physical SM count. Simple and reliable.",
                ),
            ],
            cross_verify=True,
            tolerance_pct=0,
            physical_min=1,
            physical_max=256,
        ),
        "peak_fp32_tflops": MetricSpec(
            name="peak_fp32_tflops",
            description="Peak FP32 (single-precision) throughput in TFLOPS, "
            "measured by running maximum FMA instructions across all SMs",
            unit="TFLOPS",
            strategies=[
                ProbeStrategy(
                    name="fp32_fma_throughput",
                    probe_template=None,
                    params={"FMA_ITERATIONS": 1000000, "WARMUP_ITERATIONS": 200000,
                            "TRIALS": 5, "BLOCK_SIZE": 256},
                    priority=1,
                    description="Launch FMA-heavy kernel on all SMs with max occupancy. "
                    "Each thread runs N independent FMA chains (8 chains to hide latency). "
                    "Each FMA = 2 FP32 ops. Total ops = num_threads * chains * iterations * 2. "
                    "Time with CUDA events. TFLOPS = total_ops / elapsed_sec / 1e12. "
                    "Multiple trials, take the maximum (peak).",
                ),
            ],
            cross_verify=False,
            tolerance_pct=5,
            physical_min=0.1,
            physical_max=200,
        ),
    }

    # ── Evaluation-specific metrics (ncu counter names) ──────────────
    catalog["launch__sm_count"] = MetricSpec(
        name="launch__sm_count",
        description="Number of physical SMs on the GPU, measured by launching many blocks "
        "and reading the hardware SM ID register via inline PTX",
        unit="count",
        strategies=[
            ProbeStrategy(
                name="sm_count_ptx_smid",
                probe_template=None,
                params={"GRID_SIZE": 2048, "BLOCK_SIZE": 1, "ITERATIONS": 5},
                priority=1,
                description="Launch 2048 single-thread blocks. Each block reads its SM ID using "
                "inline PTX: asm volatile(\"mov.u32 %%0, %%%%smid;\" : \"=r\"(smid)). "
                "Store all SM IDs to a device array. Copy back to host, count unique values. "
                "Repeat 5 times, take maximum unique count. Do NOT use cudaGetDeviceProperties.",
            ),
        ],
        cross_verify=False,
        tolerance_pct=0,
        physical_min=1,
        physical_max=256,
    )

    catalog["dram__bytes_read.sum.per_second"] = MetricSpec(
        name="dram__bytes_read.sum.per_second",
        description="Peak DRAM read bandwidth in bytes/second, measured by streaming reads",
        unit="bytes/s",
        strategies=[
            ProbeStrategy(
                name="dram_read_bandwidth",
                probe_template=None,
                params={"DATA_SIZE_MB": 256, "BLOCKS": 512, "THREADS": 256, "WARMUP": 5, "TRIALS": 20},
                priority=1,
                description="Allocate 256MB float array on device. Launch kernel where each thread "
                "reads sequential floats with stride. Use cudaEvent for timing. "
                "Run 20 trials, take best (minimum) time. BW = 256MB / best_time_seconds. "
                "Use const float* __restrict__ for reads. Do NOT use volatile or float4 "
                "(volatile float4 causes copy constructor errors with nvcc).",
            ),
        ],
        cross_verify=False,
        tolerance_pct=5,
        physical_min=100e9,
        physical_max=1000e9,
    )

    catalog["dram__bytes_write.sum.per_second"] = MetricSpec(
        name="dram__bytes_write.sum.per_second",
        description="Peak DRAM write bandwidth in bytes/second, measured by streaming writes",
        unit="bytes/s",
        strategies=[
            ProbeStrategy(
                name="dram_write_bandwidth",
                probe_template=None,
                params={"DATA_SIZE_MB": 256, "BLOCKS": 512, "THREADS": 256, "WARMUP": 5, "TRIALS": 20},
                priority=1,
                description="Allocate 256MB float array on device. Launch kernel where each thread "
                "writes 1.0f to sequential positions with stride. Use cudaEvent for timing. "
                "Run 20 trials, take best (minimum) time. BW = 256MB / best_time_seconds.",
            ),
        ],
        cross_verify=False,
        tolerance_pct=5,
        physical_min=100e9,
        physical_max=1000e9,
    )

    catalog["device__attribute_max_gpu_frequency_khz"] = MetricSpec(
        name="device__attribute_max_gpu_frequency_khz",
        description="Maximum GPU core clock frequency in kHz",
        unit="kHz",
        strategies=[
            ProbeStrategy(
                name="gpu_freq_nvidia_smi",
                probe_template=None,
                params={},
                priority=1,
                description="Use popen() to run: nvidia-smi --query-gpu=clocks.max.graphics "
                "--format=csv,noheader,nounits. Parse the output as double (MHz), multiply by 1000 "
                "to get kHz. Print RESULT:device__attribute_max_gpu_frequency_khz=<value>. "
                "This is a simple C program with #include <stdio.h> and <stdlib.h>. "
                "Include cuda_runtime.h for nvcc compatibility but no CUDA kernels needed.",
            ),
        ],
        cross_verify=False,
        tolerance_pct=5,
        physical_min=100000,
        physical_max=3500000,
    )

    catalog["device__attribute_max_mem_frequency_khz"] = MetricSpec(
        name="device__attribute_max_mem_frequency_khz",
        description="Maximum memory clock frequency in kHz",
        unit="kHz",
        strategies=[
            ProbeStrategy(
                name="mem_freq_nvidia_smi",
                probe_template=None,
                params={},
                priority=1,
                description="Use popen() to run: nvidia-smi --query-gpu=clocks.max.memory "
                "--format=csv,noheader,nounits. Parse the output as double (MHz), multiply by 1000 "
                "to get kHz. If that fails, try clocks.current.memory as fallback. "
                "This is a simple C program with #include <stdio.h> and <stdlib.h>.",
            ),
        ],
        cross_verify=False,
        tolerance_pct=2,
        physical_min=1000000,
        physical_max=20000000,
    )

    catalog["device__attribute_fb_bus_width"] = MetricSpec(
        name="device__attribute_fb_bus_width",
        description="Framebuffer (memory) bus width in bits",
        unit="bits",
        strategies=[
            ProbeStrategy(
                name="fb_bus_width_cuda_attr",
                probe_template=None,
                params={},
                priority=1,
                description="Call cudaDeviceGetAttribute(&value, cudaDevAttrGlobalMemoryBusWidth, 0) "
                "to get the memory bus width in bits. This is a simple program: "
                "#include <stdio.h> and <cuda_runtime.h>. Call cudaDeviceGetAttribute, "
                "then printf RESULT:device__attribute_fb_bus_width=<value>. "
                "Do NOT use cudaGetDeviceProperties. cudaDeviceGetAttribute is allowed.",
            ),
        ],
        cross_verify=False,
        tolerance_pct=0,
        physical_min=32,
        physical_max=8192,
    )

    catalog["sm__throughput.avg.pct_of_peak_sustained_elapsed"] = MetricSpec(
        name="sm__throughput.avg.pct_of_peak_sustained_elapsed",
        description="SM compute throughput as percentage of theoretical peak",
        unit="%",
        strategies=[
            ProbeStrategy(
                name="sm_throughput_fma",
                probe_template=None,
                params={"FMA_ITERS": 1000000, "BLOCKS": 512, "THREADS": 256, "WARMUP": 3, "TRIALS": 5},
                priority=1,
                description="Launch FMA-heavy kernel: each thread runs 8 independent FMA chains "
                "for 1M iterations. Total ops = BLOCKS*THREADS*8*ITERS*2. Time with cudaEvent. "
                "achieved_tflops = total_ops / best_time_sec / 1e12. "
                "RTX 3090 peak = 35.58 TFLOPS. pct = achieved/peak*100. Cap at 99.9.",
            ),
        ],
        cross_verify=False,
        tolerance_pct=10,
        physical_min=0,
        physical_max=100,
    )

    catalog["gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed"] = MetricSpec(
        name="gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed",
        description="Memory throughput as percentage of theoretical peak bandwidth",
        unit="%",
        strategies=[
            ProbeStrategy(
                name="mem_throughput_pct",
                probe_template=None,
                params={"DATA_SIZE_MB": 512, "BLOCKS": 512, "THREADS": 256, "WARMUP": 3, "TRIALS": 10},
                priority=1,
                description="Allocate 512MB on device. Launch streaming read kernel (each thread "
                "reads sequential floats with stride, accumulates sum). Time with cudaEvent. "
                "achieved_bw = 512MB / best_time_sec. RTX 3090 peak BW = 936.2 GB/s. "
                "pct = achieved_bw / peak_bw * 100. Cap at 99.9. "
                "Use const float* __restrict__ src. Do NOT use volatile float4.",
            ),
        ],
        cross_verify=False,
        tolerance_pct=10,
        physical_min=0,
        physical_max=100,
    )

    return catalog


def get_metric_spec(metric_name: str) -> MetricSpec | None:
    catalog = build_catalog()
    return catalog.get(metric_name)


def list_supported_metrics() -> list[str]:
    return list(build_catalog().keys())
