#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


VARIANT_MAP = {
    "current_best": "current_best_engine.py",
}


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description="Materialize the Phase 3 engine artifact into workspace/engine.py")
    parser.add_argument("--root", type=Path, required=True, help="Repository root")
    parser.add_argument(
        "--variant",
        default="current_best",
        choices=sorted(VARIANT_MAP.keys()),
        help="Engine source variant to render into workspace/engine.py",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    source = root / "phase3_engine_sources" / VARIANT_MAP[args.variant]
    target = root / "workspace" / "engine.py"
    target.parent.mkdir(parents=True, exist_ok=True)

    body = source.read_text(encoding="utf-8")
    header = "\n".join(
        [
            "# Auto-generated by scripts/render_phase3_engine.py",
            f"# Variant: {args.variant}",
            f"# Source: {source.relative_to(root)}",
            f"# Source-SHA256: {sha256_text(body)}",
            "",
        ]
    )
    target.write_text(header + body, encoding="utf-8")

    print(f"[pj3] generated workspace/engine.py from {source.relative_to(root)}")
    print(f"[pj3] engine variant: {args.variant}")
    print(f"[pj3] source sha256: {sha256_text(body)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
